### ISSUE TITLE
Autostart on Reveal.ready event

### ISSUE THREAD

**Issue by fghaas** [rajgoel/reveal.js#10]
I wonder if there is an option to just autostart the audio narration when the presentation has finished loading, without waiting for the user to click the play button.

If I understand correctly, then the ready event listener currently runs `setup()` and then `selectAudio()`, which will only invoke `currentAudio.play()` if invoked with the `previousAudio` parameter being non-null. That parameter is only ever set by the `ended` event which fires after the playback of an audio file — which means that audio plays automatically on every slide *except* the first.

What would be the best way to enable this? On way would be to just add an `autoplay` parameter that defaults to false, and change
```javascript
if ( previousAudio && currentAudio.id != previousAudio.id ) 
```
to
```javascript
if ( autoplay || (previousAudio && currentAudio.id != previousAudio.id) ) 
```
Does that sound reasonable?

**Comment by fghaas** [comment]
@rajgoel, if you're inclined please take a look at the referenced patch. This does exactly what I want it to do.

**Comment by fghaas** [comment]
Sorry, didn't get the logic quite right on the first try, causing autoplay to loop on the final slide. Should be fixed in 33c5aee4e0f99cb16531d12ba9987d102ca92e91.

**Comment by rajgoel** [comment]
Hi @fghaas, finally I found some time to look at this issue and am thinking of adding your patch to my code base. Usually, I find it quite annoying if webpages start playing audio automatically. Do you have a  good example for a use case for this feature?

**Comment by fghaas** [comment]
Sure, just take a look at https://hastexo.github.io/academy-openedx.

**Comment by rajgoel** [comment]
Thanks for the presentation. Looks great. I am currently doing some coding on the plugin and you will see the autoplay feature included soon.

**Comment by rajgoel** [comment]
@fghass Just curious, did you use the slideshow-recorder plugin to do the recording? The sound is excellent.

**Comment by fghaas** [comment]
I used audacity; that simplified editing. But the sound quality is probably owed to the fact that I used a decent microphone (Auna MIC-900, certainly not professional grade but excellent bang for the buck).

**Comment by rajgoel** [comment]
@fghaas I have made some changes to the plugin (primarily concering text-to-speech) and moved its location to https://github.com/rajgoel/reveal.js-plugins. Your changes are now included there (see https://github.com/rajgoel/reveal.js-plugins/tree/master/audio-slideshow#automatically-start-slideshow).

Note that this repository will no longer be maintained.

Cheers
Asvin
