### ISSUE TITLE
JS call to play/pause audio?

### ISSUE THREAD

**Issue by matbury** [rajgoel/reveal.js#11]
Is there a way to play/pause audio in audio-slideshow, i.e. the JS equivalent of the user clicking on the pause button?

e.g in a function:

Reveal.addEventListener( 'slidechanged', function() {
if(...)... [pause audio];
});

Thanks in advance! :)

**Comment by rajgoel** [comment]
Think there is no use-friendly way to that yet. What exactly do you need it for? Some time ago I was thinking of adding the possibility of providing attributes with the slides and fragments that cause the slideshow to pause. Would this be what you are looking for?

**Comment by matbury** [comment]
Yes, that'd probably be a more user-friendly way of doing it. Something like:

data-audio-src="sound.mp3" data-audio-pause="true"

or just data-audio-pause

**Comment by matbury** [comment]
Hi again, if you decide to add a more user-friendly way of pausing specific slides, please let me know. For now, I'm using some very hacky JS to do it.

Thanks for your help and for creating a great plugin! :)

**Comment by rajgoel** [comment]
Hi, I think it would be a good idea to have ```data-audio-stop="before"``` and ```data-audio-stop="after"``` for slides and fragments to stop the slideshow either before or after the audio file is played. Please go ahead if you want to create a pull request, otherwise I'll keep it on my to do list.  However, I don't know whether I'll find time for this any time soon.

**Comment by rajgoel** [comment]
Hi Matt,

I have made some changes to the plugin and moved its location to https://github.com/rajgoel/reveal.js-plugins. You can now use the attribute ```data-audio-advance="false"``` to prevent the slideshow from advancing automatically (see https://github.com/rajgoel/reveal.js-plugins/tree/master/audio-slideshow#options-for-automatically-advancing-to-next-slide).

Note that this repository will no longer be maintained.

Cheers
Asvin
