### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by oxhey** [rajgoel/reveal.js#4]
I really like the audio player . Is there  a way top skin it or show the tracking bar ?

**Comment by rajgoel** [comment]
I am glad you like it. 

Unfortunately, I don't really understand your question, could you please explain what exactly you are looking for.

**Comment by oxhey** [comment]
Well the audio player is just a play button . Is there a way to show the standard HTML5 audio player

**Comment by rajgoel** [comment]
Ok, I understand now. For the moment there is no functionality with regard to audio controls and their appearance. I am planning to extend the plugin by some customised or even customisable controls. This should not be very difficult, but unfortunately I have little time for this, so this may take very long before you will see any update :-(

**Comment by rajgoel** [comment]
I just updated the plugin so that it uses the default audio player (commit 8b5fa5dc12)

**Comment by oxhey** [comment]
Thanks . I cant figure out where i put the audio folder for it to recognise the files

**Comment by rajgoel** [comment]
You must set the <code>audioPrefix</code> and <code>audioSuffix</code> parameters, so that the audio files are found. Please check out the updated [demo](http://courses.telematique.eu/audio-slideshow/). In the demo 
<pre><code>audioPrefix: 'audio/',        // audio files are stored in the "audio" folder
audioSuffix: '.ogg',	// audio files have the ".ogg" ending</code></pre>
describes that ".ogg"-audio files are in the relative path "audio/" (don't forget the slash and the dot!)

**Comment by oxhey** [comment]
I have that . Is there a specific place for the audio folder such as in the root of the reveal presentation and is there a naming convention for the audio files.

**Comment by oxhey** [comment]
The plugin assumes that the audio name is 0.0 , 1.0 . Is there a way to make it just 0 , 1 , 2

**Comment by rajgoel** [comment]
The path should be relative to the path in which the reveal presentation lies. The naming convention is drawn from the standard reveal indices (i.e. those you can see in the URL), so "h.v" (or "h.v.f" if there are fragments), where h is the horizontal index, v is the vertical index and f is the fragment index (all starting at 0).
If you use the <code>slideshow-recorder.js</code> the files are automatically named correctly, so you don't have to worry.
