### ISSUE TITLE
Preloading

### ISSUE THREAD

**Issue by oxhey** [rajgoel/reveal.js#6]
I have added this to the js file but it dosent seem to work . All files still load .

audioElement.setAttribute( 'preload', 'none' );

**Comment by rajgoel** [comment]
In the function <code>function setupAudioElement( container, indices ) 
</code> on line 160 the audio is explicitly loaded by 
<code>audioElement.load();</code>. May be you can delete this line to 
avoid preloading (but I'm not sure whether everything works then)

Could you please explain why you want to disable preloading (I included 
it to make sure the next slide can be played)?

**Comment by oxhey** [comment]
Pre loading allot of audio files puts stress on the servers we have

**Comment by oxhey** [comment]
Removing that bit seems to work.

**Comment by rajgoel** [comment]
I justed tested and had the feeling it only works with audio files already in the cache. On a blank browser it didn't.

**Comment by oxhey** [comment]
Your right . It dosent work on a blank browser

**Comment by oxhey** [comment]
Also need it to not preload because in my case it will load a few and then the others wont load

**Comment by rajgoel** [comment]
Ok, I just committed an update that only preloads the next audio when the current audio starts playing.
